server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
    username: root
    password: Zmxncbv2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:9296

